CREATE TABLE profile (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name        VARCHAR(120) NOT NULL,
    title            VARCHAR(160) NOT NULL,
    summary          TEXT,
    avatar_url       VARCHAR(500),
    email            VARCHAR(160) NOT NULL,
    phone            VARCHAR(60),
    location         VARCHAR(120),
    github_url       VARCHAR(300),
    linkedin_url     VARCHAR(300),
    facebook_url     VARCHAR(300),
    cv_url           VARCHAR(500),
    typing_roles     TEXT,
    years_experience INT
);

CREATE TABLE skills (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(120) NOT NULL,
    category    VARCHAR(80)  NOT NULL,
    proficiency INT          NOT NULL CHECK (proficiency BETWEEN 0 AND 100),
    icon        VARCHAR(120),
    sort_order  INT          NOT NULL DEFAULT 0
);

CREATE TABLE experiences (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company     VARCHAR(160) NOT NULL,
    role        VARCHAR(160) NOT NULL,
    period      VARCHAR(64),
    description TEXT,
    tech_stack  TEXT,
    sort_order  INT NOT NULL DEFAULT 0
);

CREATE TABLE projects (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(200) NOT NULL,
    period      VARCHAR(64),
    description TEXT,
    tech_stack  TEXT,
    image_url   VARCHAR(500),
    demo_url    VARCHAR(300),
    repo_url    VARCHAR(300),
    featured    BOOLEAN NOT NULL DEFAULT FALSE,
    sort_order  INT     NOT NULL DEFAULT 0
);

CREATE TABLE education (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    school      VARCHAR(200) NOT NULL,
    degree      VARCHAR(200),
    period      VARCHAR(64),
    description TEXT,
    sort_order  INT NOT NULL DEFAULT 0
);

CREATE TABLE certifications (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(200) NOT NULL,
    issuer     VARCHAR(160),
    issued     VARCHAR(64),
    url        VARCHAR(300),
    sort_order INT NOT NULL DEFAULT 0
);

CREATE TABLE contact_messages (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name       VARCHAR(120) NOT NULL,
    email      VARCHAR(160) NOT NULL,
    subject    VARCHAR(200),
    message    TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_read    BOOLEAN   NOT NULL DEFAULT FALSE
);

CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email           VARCHAR(160) NOT NULL UNIQUE,
    password_hash   VARCHAR(100) NOT NULL,
    role            VARCHAR(30)  NOT NULL,
    failed_attempts INT          NOT NULL DEFAULT 0,
    locked_until    TIMESTAMP
);

CREATE TABLE refresh_tokens (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id    BIGINT      NOT NULL REFERENCES users (id) ON DELETE CASCADE,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    expires_at TIMESTAMP   NOT NULL,
    revoked    BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP   NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_refresh_tokens_user ON refresh_tokens (user_id);
CREATE INDEX idx_contact_messages_created ON contact_messages (created_at);
