-- Case-study fields for projects: extra screenshots and headline results.
-- gallery_urls is newline-separated (URLs may legally contain commas);
-- highlights is newline-separated bullet lines.
ALTER TABLE projects ADD COLUMN gallery_urls TEXT;
ALTER TABLE projects ADD COLUMN highlights TEXT;

CREATE TABLE testimonials (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    author     VARCHAR(120) NOT NULL,
    role       VARCHAR(160),
    quote      TEXT NOT NULL,
    avatar_url VARCHAR(500),
    sort_order INT NOT NULL DEFAULT 0
);
